// Indian Textile Heritage — Data Module

const WEAVING_TRADITIONS = [
  { id: "banarasi", name: "Banarasi Silk", origin: "Varanasi, UP", period: "Mughal Era (14th century)", description: "One of the finest silk sarees in India, known for gold and silver brocade (zari), fine silk, and opulent embroidery. Originally made for Mughal royalty.", fabric: "Pure silk with gold/silver zari", motifs: ["Floral (bel)", "Mughal jaal", "Paisley (ambi)", "Leaf vine"], process: "Handloom weaving with jacquard technique, 15-45 days per saree", certification: "GI Tagged", price: "₹5,000 – ₹5,00,000+", color: "#f59e0b", weavers: "300,000+", iconic: true },
  { id: "kanjeevaram", name: "Kanjeevaram Silk", origin: "Kanchipuram, Tamil Nadu", period: "7th Century CE (Pallava era)", description: "Heavy silk sarees with contrasting borders and rich zari work. Known for durability, vibrant colors, and temple-inspired border designs.", fabric: "Mulberry silk + silver zari", motifs: ["Temple borders (gopuram)", "Mango", "Rudraksha", "Checks", "Peacock"], process: "Two-ply silk, separate border weaving joined by pit loom", certification: "GI Tagged", price: "₹3,000 – ₹2,00,000+", color: "#ef4444", weavers: "70,000+", iconic: true },
  { id: "chanderi", name: "Chanderi Fabric", origin: "Chanderi, MP", period: "13th Century (Gond kingdom)", description: "Lightweight, sheer fabric known for its glossy texture and transparency. Combines traditional cotton weaving with silk creating a unique lightweight elegance.", fabric: "Cotton-silk blend / Pure silk", motifs: ["Coins", "Floral", "Stripes", "Mughal motifs"], process: "Pit loom weaving with open weave structure", certification: "GI Tagged", price: "₹2,000 – ₹50,000+", color: "#06b6d4", weavers: "15,000+", iconic: false },
  { id: "pochampally", name: "Pochampally Ikat", origin: "Bhoodan Pochampally, Telangana", period: "14th Century (Padmashali weavers)", description: "Unique double ikat weaving where both warp and weft are resist-dyed before weaving, creating geometric patterns that appear on both sides.", fabric: "Cotton, Silk, Cotton-silk", motifs: ["Geometric patterns", "Diamonds", "Triangles", "Temple borders"], process: "Double ikat (pre-dyed thread binding) + handloom weaving", certification: "GI Tagged", price: "₹1,500 – ₹30,000+", color: "#8b5cf6", weavers: "12,000+", iconic: false },
  { id: "patola", name: "Patola Silk", origin: "Patan, Gujarat", period: "11th Century (Solanki dynasty)", description: "Double ikat silk sarees that are reversible and symmetrical on both sides. One of the most complex weaving techniques — a single saree can take 4-6 months.", fabric: "Pure silk (double ikat)", motifs: ["Elephant", "Parrot", "Flower vase", "Walking figure", "Nari-mandir"], process: "Double ikat — both warp and weft resist-dyed to exact alignment", certification: "GI Tagged", price: "₹50,000 – ₹15,00,000", color: "#ec4899", weavers: "300+", iconic: true },
  { id: "khadi", name: "Khadi", origin: "Pan-India (Mahatma Gandhi)", period: "Ancient, revived 1920s", description: "Handspun, handwoven natural fabric. Symbol of Indian independence and self-reliance. Lightweight, breathable, gets softer with each wash.", fabric: "Cotton, Silk, Wool, Khadi blends", motifs: ["Simple checks", "Stripes", "Plain weave", "Handspun texture"], process: "Hand spinning (charkha) → Handloom weaving", certification: "Khadi India / KVIC", price: "₹200 – ₹5,000", color: "#22c55e", weavers: "Millions", iconic: true },
  { id: "muga", name: "Muga Silk", origin: "Assam", period: "Ancient (Ahom kingdom)", description: "The only golden silk in the world — naturally golden-yellow luster that increases with washing. Endemic to Assam, cannot be cultivated elsewhere.", fabric: "Muga silk (Antheraea assamensis)", motifs: ["Lotus", "River", "Dancing figure", "Traditional Assamese patterns"], process: "Sericulture (silkworm rearing) → Handloom weaving on traditional loom", certification: "GI Tagged", price: "₹5,000 – ₹1,00,000+", color: "#eab308", weavers: "30,000+", iconic: false },
  { id: "ikkat", name: "Sambalpuri Ikat", origin: "Sambalpur, Odisha", period: "Pre-colonial era", description: "Traditional bandha (ikat) sarees with symbolic motifs. The thread is tie-dyed before weaving, creating distinctive blurred-edge patterns.", fabric: "Cotton, Silk", motifs: ["Shankha (conch)", "Chakra (wheel)", "Flower", "Fish", "Temple"], process: "Traditional bandha (ikat) — tie-dye threads then handloom weave", certification: "GI Tagged", price: "₹1,500 – ₹40,000+", color: "#3b82f6", weavers: "50,000+", iconic: false },
  { id: "chikankari", name: "Chikankari", origin: "Lucknow, UP", period: "Mughal Era (Jahangir's time)", description: "Exquisite white-on-white embroidery (or colored thread) on fine muslin/organza. Subtle, delicate shadow-work creating an ethereal look.", fabric: "Fine cotton, Muslin, Organza", motifs: ["Floral", "Paisley", "Creeper (bel)", "Jaali (lattice)"], process: "36+ stitch types, hand-embroidered, often 2-4 weeks per garment", certification: "GI Tagged", price: "₹1,000 – ₹2,00,000+", color: "#94a3b8", weavers: "250,000+", iconic: false },
  { id: "kalamkari", name: "Kalamkari", origin: "Machilipatnam & Srikalahasti, AP", period: "3rd Century BCE (Satavahana)", description: "Hand-painted or block-printed cotton textile using natural dyes. Depicts mythological stories, temple art, and nature. Takes 20-30 processes to complete.", fabric: "Cotton", motifs: ["Krishna leela", "Ramayana scenes", "Floral", "Temple borders", "Peacock"], process: "Mordant treatment → Hand-painting (kalam) or block printing → Multiple washings → Natural dyeing", certification: "GI Tagged", price: "₹500 – ₹50,000+", color: "#dc2626", weavers: "3,000+", iconic: false },
  { id: "kota-doria", name: "Kota Doria", origin: "Kota, Rajasthan", period: "17th Century", description: "Extremely lightweight, translucent cotton fabric with characteristic square checks (khat). Called 'kota masuria' — so light it can pass through a ring.", fabric: "Cotton (count 60-80)", motifs: ["Checks (khat)", "Borders", "Simple zari work"], process: "Pit loom weaving with cotton warp, fine cotton weft creating gossamer-like fabric", certification: "GI Tagged", price: "₹800 – ₹15,000+", color: "#818cf8", weavers: "10,000+", iconic: false },
  { id: "kanchi-cotton", name: "Kanchi Cotton", origin: "Kanchipuram, Tamil Nadu", period: "Ancient (Chola period)", description: "Traditional handloom cotton sarees from Kanchipuram, known for temple borders and traditional patterns. Lighter and more affordable than their silk counterparts.", fabric: "Fine cotton", motifs: ["Temple borders", "Mango", "Peacock", "Stripes"], process: "Pit loom weaving with traditional patterns, 7-15 days per saree", certification: "GI Tagged", price: "₹800 – ₹5,000+", color: "#f97316", weavers: "5,000+", iconic: false },
];

const EMBROIDERY_STYLES = [
  { id: "chikankari", name: "Chikankari", origin: "Lucknow, UP", description: "Delicate white shadow-work embroidery with 36+ stitch types on fine muslin. A Mughal art form creating ethereal, translucent patterns.", stitches: ["Murri (French knot)", "Phanda (turban)", "Jali (lattice)", "Keel (backstitch)", "Hool (eyelet)", "Tepchi (running)"], usage: ["Sarees", "Kurtas", "Sharara", "Dupatta", "Table linen"], difficulty: "Master", color: "#e2e8f0" },
  { id: "kantha", name: "Kantha Stitching", origin: "West Bengal & Bangladesh", description: "Running stitch embroidery creating quilted fabric from old sarees. Depicts folk stories, mythology, nature. Each piece is unique and tells a story.", stitches: ["Running stitch (kantha)", "Darn stitch", "Stem stitch"], usage: ["Quilts ( nakshi kantha)", "Sarees", "Bedspreads", "Wall hangings"], difficulty: "Intermediate", color: "#f59e0b" },
  { id: "phulkari", name: "Phulkari", origin: "Punjab", description: "Vibrant floral embroidery on coarse cotton (khaddar) using darning stitch from the wrong side. Creates vivid geometric and floral patterns.", stitches: ["Darning stitch (unt deluxe)", "Herringbone", "Chain stitch"], usage: ["Dupattas", "Shawls (chopes)", "Pillows", "Bags"], difficulty: "Intermediate", color: "#ef4444" },
  { id: "kashida", name: "Kashida (Kashmiri)", origin: "Kashmir", description: "Aari embroidery using a hooked needle (aar) creating chain-stitch patterns of flowers, birds, and chinar leaves. Soft, flowing, nature-inspired.", stitches: ["Aari chain stitch", "Satin stitch", "Stalk stitch", "Dodec stitch"], usage: ["Shawls (pashmina)", "Pherans", "Caps (taranga)", "Cushions"], difficulty: "Advanced", color: "#06b6d4" },
  { id: "maggam", name: "Maggam / Aari Work", origin: "Andhra Pradesh & Tamil Nadu", description: "Rich, heavy embroidery using aari needle creating elaborate patterns with beads, stones, and sequins on silk and velvet. Used for bridal and festive wear.", stitches: ["Aari chain stitch", "Zardozi", "French knots", "Cutwork"], usage: ["Bridal blouses", "Lehengas", "Saree borders", "Jewelry"], difficulty: "Advanced", color: "#a855f7" },
  { id: "gotta-patti", name: "Gotta Patti", origin: "Rajasthan", description: "Gold/silver ribbon (gota) appliqué work creating raised patterns. Applied in strips and cut into shapes — flowers, peacocks, leaves. Glittering and festive.", stitches: ["Gota appliqué", "Lappa work", "Dori work"], usage: ["Lehengas", "Dupattas", "Odhnis", "Bridal wear"], difficulty: "Intermediate", color: "#eab308" },
  { id: "mirror-work", name: "Shisha (Mirror Work)", origin: "Gujarat & Rajasthan", description: "Small mirrors (shisha) embroidered into fabric using chain stitches creating sparkling, reflective patterns. Originally used to deflect evil eye.", stitches: ["Shisha stitch (mirror attachment)", "Chain stitch", "Herringbone"], usage: ["Choli blouses", "Bags", "Wall hangings", "Kutch embroidery"], difficulty: "Beginner to Intermediate", color: "#22c55e" },
];

const TEXTILE_CRAFTS = [
  { id: "block-printing", name: "Block Printing", origin: "Rajasthan (Jaipur, Sanganer, Bagru)", description: "Hand-carved wooden blocks dipped in natural dyes and pressed onto fabric. Each block is a work of art. Used for centuries to create patterns on cotton and silk.", tools: ["Teak wood blocks", "Natural dyes", "Printing table", "Fixing mordants"], dyes: ["Indigo", "Turmeric", "Madder root", "Pomegranate", "Iron rust"], color: "#f59e0b" },
  { id: "batik", name: "Batik", origin: "Gujarat ( Ahmedabad, Baroda)", description: "Wax-resist dyeing technique where hot wax is applied to fabric before dyeing, creating crackled patterns. Multiple waxing and dyeing cycles create complex designs.", tools: ["Canting (wax pen)", "Tjanting", "Natural dyes", "Beeswax"], dyes: ["Indigo", "Madder", "Turmeric", "Iron"], color: "#3b82f6" },
  { id: "bandhani", name: "Bandhani (Tie-Dye)", origin: "Rajasthan & Gujarat", description: "Fabric tied in thousands of tiny knots before dyeing. Creates intricate dot patterns. The finer the dots, the more valuable the textile.", tools: ["Fingernails (traditional)", "Tweezers", "Natural dyes", "Thread"], dyes: ["Red (alizarin)", "Yellow (turmeric)", "Blue (indigo)"], color: "#ef4444" },
  { id: "zardozi", name: "Zardozi", origin: "Lucknow & Delhi (Mughal)", description: "Heavy gold and silver thread embroidery with precious stones. The most opulent form of Indian embroidery. Used for royal garments and bridal wear.", tools: ["Gold/silver thread (tilla)", "Aari needle", "Dabka", "Sequin stones"], dyes: ["Gold thread", "Silver thread", "Copper thread"], color: "#eab308" },
  { id: "tassar", name: "Tussar Silk Processing", origin: "Jharkhand, Bihar, MP", description: "Wild silk harvesting and processing. Tussar silkworms feed on oak and arjun leaves, producing naturally golden-hued silk. A forest-based livelihood for tribal communities.", tools: ["Cocoon harvesting", "Hand reeling", "Traditional looms"], dyes: ["Natural gold", "Vegetable dyes", "Mineral dyes"], color: "#f97316" },
];

const TEXTILE_STATISTICS = [
  { value: "₹3.5L Cr", label: "Indian Textile Market Size (2026)", icon: "📊", color: "#f59e0b" },
  { value: "45M+", label: "People Employed in Handlooms", icon: "👥", color: "#22c55e" },
  { value: "28", label: "GI-Tagged Textiles", icon: "🏷️", color: "#06b6d4" },
  { value: "1,000+", label: "Handloom Cooperatives", icon: "🏛️", color: "#a855f7" },
  { value: "₹11,000 Cr", label: "Annual Handloom Exports", icon: "🌍", color: "#ec4899" },
  { value: "2,500+ Yrs", label: "Oldest Textile Traditions", icon: "⏳", color: "#ef4444" },
];

const SUSTAINABILITY_FACTS = [
  { title: "Zero Carbon Footprint", icon: "🌱", body: "Handloom weaving produces 95% less CO₂ than powerloom mills. No electricity needed — purely human-powered. India's 2.4M handlooms are the world's largest zero-carbon manufacturing sector.", color: "#22c55e" },
  { title: "Natural Dyes Revival", icon: "🎨", body: "Traditional Indian textiles used plant-based dyes: indigo (blue), madder (red), turmeric (yellow), pomegranate (green). These biodegradable dyes are making a comeback as sustainable fashion grows.", color: "#06b6d4" },
  { title: "Supporting Rural Livelihoods", icon: "🏘️", body: "Handloom weaving supports 4.3 million families across 58,000+ villages. Each saree generates employment for 10-15 artisans from spinning to finishing.", color: "#f59e0b" },
  { title: "Circular Economy Pioneer", icon: "♻️", body: "Indian textiles have always been circular — Khadi was literally made from recycled fibers, Kantha quilts repurpose old sarees, and natural dyes compost naturally.", color: "#8b5cf6" },
  { title: "Water Conservation", icon: "💧", body: "Handloom weaving uses 10-50x less water than industrial textile production. Traditional dyeing methods are water-efficient and pollution-free.", color: "#3b82f6" },
  { title: "Cultural Preservation", icon: "🏺", body: "Each GI-tagged textile preserves centuries of knowledge. When you buy a Patola, you support the last 300 families maintaining a 900-year-old art form.", color: "#ec4899" },
];
