/**
 * National Parks of India Explorer — Data
 * Comprehensive dataset covering parks, tiger reserves, UNESCO sites,
 * wildlife species, and geographic coordinates for map markers.
 */

const NATIONAL_PARKS = [
    {
        id: 'rajaji',
        name: 'Rajaji National Park',
        state: 'Uttarakhand',
        stateId: 'uk',
        established: 1983,
        area: 820,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description: 'Spread across the Shivalik Hills, Rajaji is famous for its large population of Asian elephants and diverse Shivalik ecosystem. It was formed by merging three sanctuaries.',
        keyFauna: ['Asian Elephant', 'Bengal Tiger', 'Leopard', 'Himalayan Black Bear', 'Sambar'],
        keyFlora: ['Sal Forest', 'Shisham', 'Khair', 'Tall Grasslands'],
        coordinates: { lat: 30.05, lng: 78.15 },
        climate: 'Subtropical',
        bestTime: 'November to June',
        entryFee: '₹150 (Indian), ₹600 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Elephants_in_Rajaji_National_Park.jpg/960px-Elephants_in_Rajaji_National_Park.jpg',
        explorerUrl: '../rajaji-national-park-explorer/index.html'
    },
    {
        id: 'jim-corbett',
        name: 'Jim Corbett National Park',
        state: 'Uttarakhand',
        stateId: 'ut',
        established: 1936,
        area: 1318,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            "India's oldest national park, established as Hailey National Park. It played a pioneering role in Project Tiger (1973) and protects pristine sub-Himalayan biodiversity.",
        keyFauna: ['Bengal Tiger', 'Asian Elephant', 'Leopard', 'Chital', 'Peafowl'],
        keyFlora: ['Sal Forests', 'Riverine', 'Chir Pine'],
        coordinates: { lat: 29.53, lng: 78.77 },
        climate: 'Subtropical',
        bestTime: 'November to June',
        entryFee: '₹200 (Indian), ₹1000 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Jim_Corbett_National_Park_%28India%29.jpg/960px-Jim_Corbett_National_Park_%28India%29.jpg'
    },
    {
        id: 'kaziranga',
        name: 'Kaziranga National Park',
        state: 'Assam',
        stateId: 'as',
        established: 1974,
        area: 858,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: true,
        description:
            "UNESCO World Heritage Site hosting two-thirds of the world's Great Indian One-Horned Rhinoceroses. Features dense tall elephant grasslands and wetlands.",
        keyFauna: ['One-Horned Rhinoceros', 'Wild Water Buffalo', 'Swamp Deer', 'Bengal Tiger', 'Asian Elephant'],
        keyFlora: ['Tropical Semi-Evergreen', 'Tropical Moist Deciduous'],
        coordinates: { lat: 26.64, lng: 93.42 },
        climate: 'Subtropical Monsoon',
        bestTime: 'November to April',
        entryFee: '₹650 (Indian), ₹2500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Elephant_safari_in_Kaziranga.jpg/960px-Elephant_safari_in_Kaziranga.jpg',
        explorerUrl: '../kaziranga-national-park-explorer/index.html'
    },
    {
        id: 'ranthambore',
        name: 'Ranthambore National Park',
        state: 'Rajasthan',
        stateId: 'rj',
        established: 1980,
        area: 1334,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            'Famous for its tigers, which are highly active in daylight. The landscape is dotted with historical ruins, including the dramatic Ranthambore Fort.',
        keyFauna: ['Bengal Tiger', 'Leopard', 'Sloth Bear', 'Chital', 'Marsh Crocodile'],
        keyFlora: ['Dhok Tree', 'Banyan', 'Neem'],
        coordinates: { lat: 26.02, lng: 76.5 },
        climate: 'Semi-Arid',
        bestTime: 'October to June',
        entryFee: '₹140 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Padam_Talao_Lake%2C_Ranthambore_National_Park_%282014%29.jpg/960px-Padam_Talao_Lake%2C_Ranthambore_National_Park_%282014%29.jpg'
    },
    {
        id: 'kanha',
        name: 'Kanha National Park',
        state: 'Madhya Pradesh',
        stateId: 'mp',
        established: 1955,
        area: 940,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            "Famous for saving the hard-ground Barasingha from near-extinction. Its lush sal forests and open meadows inspired Rudyard Kipling's The Jungle Book.",
        keyFauna: ['Bengal Tiger', 'Barasingha', 'Leopard', 'Dhole', 'Blackbuck'],
        keyFlora: ['Sal Forest', 'Bamboo', 'Grasslands'],
        coordinates: { lat: 22.34, lng: 80.61 },
        climate: 'Tropical Dry Deciduous',
        bestTime: 'October to June',
        entryFee: '₹150 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Jungle_safari_-_Kanha_National_Park.jpg/960px-Jungle_safari_-_Kanha_National_Park.jpg'
    },
    {
        id: 'kuno',
        name: 'Kuno National Park',
        state: 'Madhya Pradesh',
        stateId: 'mp',
        established: 2018,
        area: 748,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description: 'Globally recognized for the historic African Cheetah reintroduction project (Project Cheetah). Features dry deciduous forests, grasslands, and a growing prey base.',
        keyFauna: ['African Cheetah', 'Bengal Tiger', 'Leopard', 'Sloth Bear', 'Chital'],
        keyFlora: ['Khair', 'Salar', 'Teak', 'Grasslands'],
        coordinates: { lat: 25.85, lng: 77.35 },
        climate: 'Tropical Dry Deciduous',
        bestTime: 'October to March',
        entryFee: '₹50 (Indian), ₹200 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Acinonyx_jubatus_2.jpg/960px-Acinonyx_jubatus_2.jpg',
        explorerUrl: '../kuno-national-park-explorer/index.html'
    },
    {
        id: 'bandhavgarh',
        name: 'Bandhavgarh National Park',
        state: 'Madhya Pradesh',
        stateId: 'mp',
        established: 1968,
        area: 1536,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            'Known for the highest concentration of Royal Bengal Tigers in India. The park is named after an ancient fort perched on an 800-meter hill at its center.',
        keyFauna: ['Bengal Tiger', 'Leopard', 'Gaur', 'Sambar', 'Nilgai'],
        keyFlora: ['Sal', 'Bamboo', 'Dhobin'],
        coordinates: { lat: 23.72, lng: 80.96 },
        climate: 'Subtropical',
        bestTime: 'October to June',
        entryFee: '₹150 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/1_Bandhavgarh_National_Park_Madhya_Pradesh_India.jpg/960px-1_Bandhavgarh_National_Park_Madhya_Pradesh_India.jpg'
    },
    {
        id: 'periyar',
        name: 'Periyar National Park',
        state: 'Kerala',
        stateId: 'kl',
        established: 1982,
        area: 925,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            'Centered on an artificial lake in the Western Ghats. Famous for scenic boat-safari wildlife viewing and spice valley contours.',
        keyFauna: ['Asian Elephant', 'Bengal Tiger', 'Nilgiri Langur', 'Lion-Tailed Macaque', 'Gaur'],
        keyFlora: ['Tropical Evergreen', 'Semi-Evergreen', 'Shola Forests'],
        coordinates: { lat: 9.46, lng: 77.15 },
        climate: 'Tropical Monsoon',
        bestTime: 'September to March',
        entryFee: '₹45 (Indian), ₹500 (Foreign)',
        explorerUrl: '../periyar-national-park-explorer/index.html',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Periyar_National_Park_02.jpg/960px-Periyar_National_Park_02.jpg'
    },
    {
        id: 'sundarbans',
        name: 'Sundarbans National Park',
        state: 'West Bengal',
        stateId: 'wb',
        established: 1984,
        area: 1330,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: true,
        description:
            'The largest mangrove delta forest in the world, split with Bangladesh. The tigers here are famous for having adapted to swimming in saline river tides.',
        keyFauna: ['Bengal Tiger', 'Estuarine Crocodile', 'Olive Ridley Turtle', 'Ganges River Dolphin', 'Fishing Cat'],
        keyFlora: ['Sundari Mangrove', 'Golpata', 'Genwa'],
        coordinates: { lat: 21.95, lng: 88.95 },
        climate: 'Tropical Monsoon',
        bestTime: 'September to March',
        entryFee: '₹200 (Indian), ₹1000 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Sundarbans_National_Park.jpg/960px-Sundarbans_National_Park.jpg'
    },
    {
        id: 'valmiki',
        name: 'Valmiki National Park',
        state: 'Bihar',
        stateId: 'br',
        established: 1990,
        area: 898,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description: "Bihar's only National Park and a critical Tiger Reserve. Located in the Terai region at the Himalayan foothills, it features rich Sal forests, tall grasslands, and the Gandak River.",
        keyFauna: ['Bengal Tiger', 'Asian Elephant', 'Sloth Bear', 'Hispid Hare', 'Pygmy Hog', 'Gangetic Dolphin'],
        keyFlora: ['Sal Forest', 'Tall Grasslands', 'Riverine Vegetation', 'Shisham'],
        coordinates: { lat: 27.35, lng: 83.95 },
        climate: 'Subtropical Monsoon',
        bestTime: 'November to April',
        entryFee: '₹100 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Royal_Bengal_Tiger_at_Nandankanan.jpg/960px-Royal_Bengal_Tiger_at_Nandankanan.jpg',
        explorerUrl: '../valmiki-national-park-explorer/index.html'
    },
    {
        id: 'gir',
        name: 'Gir National Park & Sanctuary',
        state: 'Gujarat',
        stateId: 'gj',
        established: 1965,
        area: 1412,
        areaUnit: 'km²',
        type: 'Wildlife Sanctuary',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            'The sole natural sanctuary in the world for the Asiatic Lion. A highly successful conservation model that brought the population back from under 20 individuals.',
        keyFauna: ['Asiatic Lion', 'Leopard', 'Sambar', 'Chowsingha', 'Indian Gazelle'],
        keyFlora: ['Teak', 'Acacia', 'Banyan'],
        coordinates: { lat: 21.14, lng: 70.82 },
        climate: 'Tropical Dry',
        bestTime: 'October to June',
        entryFee: '₹100 (Indian), ₹800 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Majestic_Asiatic_Lions_in_Devalia_Safari_Park%2C_Gir_National_Forest_Park.jpg/960px-Majestic_Asiatic_Lions_in_Devalia_Safari_Park%2C_Gir_National_Forest_Park.jpg'
    },
    {
        id: 'keoladeo',
        name: 'Keoladeo National Park',
        state: 'Rajasthan',
        stateId: 'rj',
        established: 1982,
        area: 29,
        areaUnit: 'km²',
        type: 'Bird Sanctuary',
        isTigerReserve: false,
        isUNESCO: true,
        description:
            'Formerly Bharatpur Bird Sanctuary, it is a man-made wetland hosting thousands of migratory waterfowl. A UNESCO World Heritage Site.',
        keyFauna: ['Siberian Crane', 'Painted Stork', 'Sambar', 'Python', 'Mugger Crocodile'],
        keyFlora: ['Babul', 'Ber', 'Kair'],
        coordinates: { lat: 27.17, lng: 77.49 },
        climate: 'Semi-Arid',
        bestTime: 'August to November',
        entryFee: '₹50 (Indian), ₹400 (Foreign)',
        explorerUrl: '../keoladeo-national-park-explorer/index.html',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Keoladeo_Ghana_National_Park%2C_Bharatpur%2C_Rajasthan%2C_India.jpg/960px-Keoladeo_Ghana_National_Park%2C_Bharatpur%2C_Rajasthan%2C_India.jpg'
    },
    {
        id: 'hemis',
        name: 'Hemis National Park',
        state: 'Ladakh',
        stateId: 'jk',
        established: 1981,
        area: 4400,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            "India's largest national park. Located in the high-altitude trans-Himalayas, it is globally renowned for having the highest density of Snow Leopards.",
        keyFauna: ['Snow Leopard', 'Argali', 'Bharal', 'Tibetan Wolf', 'Golden Eagle'],
        keyFlora: ['Juniper', 'Alder', 'Willow'],
        coordinates: { lat: 33.95, lng: 77.4 },
        climate: 'Cold Desert',
        bestTime: 'June to September',
        entryFee: '₹30 (Indian), ₹300 (Foreign)',
        explorerUrl: '../hemis-national-park-explorer/index.html',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Hemis_national_park.jpg/960px-Hemis_national_park.jpg'
    },
    {
        id: 'great-himalayan',
        name: 'Great Himalayan National Park',
        state: 'Himachal Pradesh',
        stateId: 'hp',
        established: 1984,
        area: 1171,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: true,
        description:
            'A UNESCO World Heritage Site preserving high-altitude Himalayan oak and alpine forests. Features unique fauna like the Western Tragopan pheasant.',
        keyFauna: ['Western Tragopan', 'Snow Leopard', 'Himalayan Musk Deer', 'Himalayan Tahr', 'Snowcock'],
        keyFlora: ['Western Mixed Oak', 'Deodar Cedar', 'Blue Pine'],
        coordinates: { lat: 31.57, lng: 77.38 },
        climate: 'Alpine Subarctic',
        bestTime: 'March to June',
        entryFee: '₹100 (Indian), ₹600 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Great_Himalayan_National_Park_Mountain_View.jpg/960px-Great_Himalayan_National_Park_Mountain_View.jpg'
    },
    {
        id: 'valley-of-flowers',
        name: 'Valley of Flowers National Park',
        state: 'Uttarakhand',
        stateId: 'ut',
        established: 1982,
        area: 87,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: true,
        description:
            'Nestled in West Himalayas, famous for meadows of endemic alpine flowers. Along with Nanda Devi, it forms a UNESCO World Heritage Site.',
        keyFauna: ['Musk Deer', 'Snow Leopard', 'Himalayan Black Bear', 'Red Fox', 'Himalayan Monal'],
        keyFlora: ['Brahma Kamal', 'Blue Poppy', 'Cobra Lily', 'Alpine Meadows'],
        coordinates: { lat: 30.73, lng: 79.61 },
        climate: 'Alpine',
        bestTime: 'July to September',
        entryFee: '₹150 (Indian), ₹600 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Pushpawati_river_inside_the_Valley_of_Flowers_Uttarakhand_I.jpg/960px-Pushpawati_river_inside_the_Valley_of_Flowers_Uttarakhand_I.jpg'
    },
    {
        id: 'namdapha',
        name: 'Namdapha National Park',
        state: 'Arunachal Pradesh',
        stateId: 'ar',
        established: 1983,
        area: 1985,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            'India’s 4th largest national park and biodiversity hotspot in Arunachal Pradesh, famous for harbouring four big cat species and Red Pandas.',
        keyFauna: ['Snow Leopard', 'Clouded Leopard', 'Red Panda', 'Bengal Tiger', 'Hoolock Gibbon'],
        keyFlora: ['Hollong', 'Dipterocarps', 'Blue Vanda Orchids'],
        coordinates: { lat: 27.49, lng: 96.38 },
        climate: 'Subtropical Monsoon',
        bestTime: 'October to April',
        entryFee: '₹50 (Indian), ₹500 (Foreign)',
        explorerUrl: '../namdapha-national-park-explorer/index.html',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Neofelis_nebulosa.jpg/960px-Neofelis_nebulosa.jpg'
    },
    {
        id: 'nanda-devi',
        name: 'Nanda Devi National Park',
        state: 'Uttarakhand',
        stateId: 'ut',
        established: 1982,
        area: 630,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: true,
        description:
            "Surrounds the peak of Nanda Devi (India's second highest). It is a glacial basin protected by steep mountain ridges, keeping it highly pristine.",
        keyFauna: ['Snow Leopard', 'Himalayan Tahr', 'Bharal', 'Musk Deer', 'Brown Bear'],
        keyFlora: ['Birch', 'Juniper', 'Alpine Meadows'],
        coordinates: { lat: 30.4, lng: 79.6 },
        climate: 'Alpine',
        bestTime: 'May to September',
        entryFee: '₹150 (Indian), ₹600 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Nanda_Devi_Biosphere_Reserve_-_Chamoli.jpg/960px-Nanda_Devi_Biosphere_Reserve_-_Chamoli.jpg'
    },
    {
        id: 'dudhwa',
        name: 'Dudhwa National Park',
        state: 'Uttar Pradesh',
        stateId: 'up',
        established: 1977,
        area: 490,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            'Crown jewel of the Terai Arc in Uttar Pradesh, famous for holding 50% of the world’s Swamp Deer (Barasingha) and reintroduced One-horned Rhinos.',
        keyFauna: ['Barasingha (Swamp Deer)', 'One-Horned Rhinoceros', 'Bengal Tiger', 'Asian Elephant', 'Gangetic Dolphin'],
        keyFlora: ['Sal Forest', 'Elephant Grass', 'Narkul', 'Jamun'],
        coordinates: { lat: 28.49, lng: 80.65 },
        climate: 'Subtropical Monsoon',
        bestTime: 'November to April',
        entryFee: '₹100 (Indian), ₹500 (Foreign)',
        explorerUrl: '../dudhwa-national-park-explorer/index.html',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Swamp_Deer_Barasingha.jpg/960px-Swamp_Deer_Barasingha.jpg'
    },
    {
        id: 'simlipal',
        name: 'Simlipal National Park',
        state: 'Odisha',
        stateId: 'or',
        established: 1980,
        area: 2750,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: true,
        description:
            "A UNESCO Biosphere Reserve in Odisha, famous for Barehipani waterfall (399m), world's only melanistic black tigers, and Mayurbhanj elephants.",
        keyFauna: ['Melanistic Black Tiger', 'Asian Elephant', 'Sambar Deer', 'Mugger Crocodile', 'Hill Myna'],
        keyFlora: ['Sal Forest', 'Red Silk Cotton (Simul)', 'Epiphytic Orchids', 'Jamun'],
        coordinates: { lat: 21.93, lng: 86.35 },
        climate: 'Tropical Monsoon',
        bestTime: 'November to June',
        entryFee: '₹100 (Indian), ₹500 (Foreign)',
        explorerUrl: '../simlipal-national-park-explorer/index.html',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Neofelis_nebulosa.jpg/960px-Neofelis_nebulosa.jpg'
    },
    {
        id: 'manas',
        name: 'Manas National Park',
        state: 'Assam',
        stateId: 'as',
        established: 1990,
        area: 950,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: true,
        description:
            'A UNESCO World Heritage Site, Biosphere Reserve, and Elephant Reserve in Assam, famous for Golden Langurs, Pygmy Hogs, and the Manas River.',
        keyFauna: ['Golden Langur', 'Pygmy Hog', 'Bengal Tiger', 'Wild Water Buffalo', 'Asian Elephant'],
        keyFlora: ['Semi-Evergreen Forest', 'Alluvial Grassland', 'Elephant Grass'],
        coordinates: { lat: 26.65, lng: 91.0 },
        climate: 'Tropical Monsoon',
        bestTime: 'October to April',
        entryFee: '₹100 (Indian), ₹500 (Foreign)',
        explorerUrl: '../manas-national-park-explorer/index.html',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Golden_Langur_Manas.jpg/960px-Golden_Langur_Manas.jpg'
    },
    {
        id: 'bandipur',
        name: 'Bandipur National Park',
        state: 'Karnataka',
        stateId: 'ka',
        established: 1974,
        area: 874,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            'Part of the Nilgiri Biosphere Reserve, this dry deciduous forest holds a significant population of endangered Asian Elephants.',
        keyFauna: ['Asian Elephant', 'Bengal Tiger', 'Gaur', 'Chital', 'Peafowl'],
        keyFlora: ['Teak', 'Rosewood', 'Sandalwood'],
        coordinates: { lat: 11.65, lng: 76.62 },
        climate: 'Tropical Monsoon',
        bestTime: 'October to March',
        entryFee: '₹80 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Bandipur_National_Park%2C_Karnataka%2C_Wild_Elephants.jpg/960px-Bandipur_National_Park%2C_Karnataka%2C_Wild_Elephants.jpg'
    },
    {
        id: 'nagarhole',
        name: 'Nagarhole National Park',
        state: 'Karnataka',
        stateId: 'ka',
        established: 1988,
        area: 643,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            "Also known as Rajiv Gandhi National Park. One of India's finest wildlife reserves with dense forests and abundant water bodies.",
        keyFauna: ['Bengal Tiger', 'Asian Elephant', 'Indian Leopard', 'Dhole', 'Gaur'],
        keyFlora: ['Teak', 'Rosewood', 'Sandalwood', 'Silver Oak'],
        coordinates: { lat: 12.08, lng: 76.23 },
        climate: 'Tropical Monsoon',
        bestTime: 'October to May',
        entryFee: '₹80 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Male_Elephant_Tusker_Nagarhole_Karnataka_Apr22_D72_23736.jpg/960px-Male_Elephant_Tusker_Nagarhole_Karnataka_Apr22_D72_23736.jpg'
    },
    {
        id: 'tadoba',
        name: 'Tadoba Andhari Tiger Reserve',
        state: 'Maharashtra',
        stateId: 'mh',
        established: 1955,
        area: 625,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            "Maharashtra's oldest national park. Features dense teak and bamboo forests, and the central Tadoba Lake as a vital water source.",
        keyFauna: ['Bengal Tiger', 'Leopard', 'Sloth Bear', 'Gaur', 'Indian Crocodile'],
        keyFlora: ['Teak', 'Bamboo', 'Ain'],
        coordinates: { lat: 20.23, lng: 79.45 },
        climate: 'Tropical Dry',
        bestTime: 'October to June',
        entryFee: '₹100 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Matkasur_the_male_tiger_at_Tadoba_Andhari_Tiger_Reserve.jpg/960px-Matkasur_the_male_tiger_at_Tadoba_Andhari_Tiger_Reserve.jpg'
    },
    {
        id: 'pench',
        name: 'Pench National Park',
        state: 'Madhya Pradesh',
        stateId: 'mp',
        established: 1975,
        area: 758,
        areaUnit: 'km²',
        type: 'Tiger Reserve',
        isTigerReserve: true,
        isUNESCO: false,
        description:
            'Named after the pristine Pench River that flows through the park. Highly regarded for its rich bird population and open canopy teak forests.',
        keyFauna: ['Bengal Tiger', 'Leopard', 'Gaur', 'Barking Deer', 'Indian Wolf'],
        keyFlora: ['Teak', 'Mahua', 'Bamboo'],
        coordinates: { lat: 21.74, lng: 79.29 },
        climate: 'Tropical Dry',
        bestTime: 'October to May',
        entryFee: '₹100 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Pench_National_Park%2C_Madhya_Pradesh_-_by_Ishani_Mehta.jpg/960px-Pench_National_Park%2C_Madhya_Pradesh_-_by_Ishani_Mehta.jpg'
    },
    {
        id: 'dachigam',
        name: 'Dachigam National Park',
        state: 'Jammu and Kashmir',
        stateId: 'jk',
        established: 1981,
        area: 141,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            'Located near Srinagar, it is the last remaining home of the Hangul (Kashmir Stag), which is critically endangered.',
        keyFauna: ['Hangul', 'Himalayan Black Bear', 'Snow Leopard', 'Leopard', 'Musk Deer'],
        keyFlora: ['Cedar', 'Pine', 'Walnut'],
        coordinates: { lat: 34.18, lng: 75.02 },
        climate: 'Temperate',
        bestTime: 'April to September',
        entryFee: '₹30 (Indian), ₹300 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/A_view_of_Lower_Dachigam_where_most_of_the_hangul_get_confined_in_winter%2C_AJT_Johnsingh.jpg/960px-A_view_of_Lower_Dachigam_where_most_of_the_hangul_get_confined_in_winter%2C_AJT_Johnsingh.jpg',
        explorerUrl: '../dachigam-national-park-explorer/index.html'
    },
    {
        id: 'desert',
        name: 'Desert National Park',
        state: 'Rajasthan',
        stateId: 'rj',
        established: 1992,
        area: 3162,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            'Showcases Thar desert ecosystems, featuring shifting sand dunes and scrub forest. One of the last strongholds of the critically endangered Great Indian Bustard.',
        keyFauna: ['Great Indian Bustard', 'Desert Fox', 'Chinkara', 'Sandgrouse', 'Blackbuck'],
        keyFlora: ['Prosopis Cineraria', 'Calligonum', 'Tamarix'],
        coordinates: { lat: 26.85, lng: 70.9 },
        climate: 'Hot Desert',
        bestTime: 'November to March',
        entryFee: '₹50 (Indian), ₹300 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Desert_vegetation_DSC0942.jpg/960px-Desert_vegetation_DSC0942.jpg'
    },
    {
        id: 'silent-valley',
        name: 'Silent Valley National Park',
        state: 'Kerala',
        stateId: 'kl',
        established: 1984,
        area: 237,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            'Contains some of the last undisturbed tropical evergreen rainforests in India. Famously saved in the 1970s from a hydroelectric project.',
        keyFauna: ['Lion-Tailed Macaque', 'Nilgiri Wood Pigeon', 'Tiger', 'Nilgiri Langur', 'Malabar Giant Squirrel'],
        keyFlora: ['Tropical Evergreen', 'Shola Forests', 'Grasslands'],
        coordinates: { lat: 11.13, lng: 76.37 },
        climate: 'Tropical Monsoon',
        bestTime: 'October to May',
        entryFee: '₹50 (Indian), ₹400 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Bhavani_puzha_-_silent_valley.jpg/960px-Bhavani_puzha_-_silent_valley.jpg'
    },
    {
        id: 'eravikulam',
        name: 'Eravikulam National Park',
        state: 'Kerala',
        stateId: 'kl',
        established: 1978,
        area: 97,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            "Located in Munnar's high elevation shola forests. It protects the largest remaining population of the Nilgiri Tahr, a mountain goat endemic to Western Ghats.",
        keyFauna: ['Nilgiri Tahr', 'Golden Jackal', 'Leopard', 'Sambar', 'Atlas Moth'],
        keyFlora: ['Shola Forest', 'Grasslands', 'Tea Plantations'],
        coordinates: { lat: 10.19, lng: 77.06 },
        climate: 'Tropical Montane',
        bestTime: 'September to November',
        entryFee: '₹120 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Nilgiri_Tahr_Eravikulam_National_Park.jpg/960px-Nilgiri_Tahr_Eravikulam_National_Park.jpg'
    },
    {
        id: 'bannerghatta',
        name: 'Bannerghatta National Park',
        state: 'Karnataka',
        stateId: 'ka',
        established: 1974,
        area: 260,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            'Located near Bengaluru, it includes a national park, a zoo, a butterfly park, and a biological reserve that serves as an important elephant corridor.',
        keyFauna: ['Asian Elephant', 'Bengal Tiger', 'Leopard', 'Sloth Bear', 'Peafowl'],
        keyFlora: ['Tropical Dry Deciduous', 'Scrub Forest', 'Eucalyptus'],
        coordinates: { lat: 12.8, lng: 77.58 },
        climate: 'Tropical Savanna',
        bestTime: 'October to May',
        entryFee: '₹80 (Indian), ₹400 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Bannerghatta_National_Park_4-24-2011_1-09-20_PM.JPG/960px-Bannerghatta_National_Park_4-24-2011_1-09-20_PM.JPG',
        explorerUrl: '../bannerghatta-national-park-explorer/index.html'
    },
    {
        id: 'madhav',
        name: 'Madhav National Park',
        state: 'Madhya Pradesh',
        stateId: 'mp',
        established: 1958,
        area: 354,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            'Located in the historical region of Shivpuri. Features dry deciduous forests and served as a royal hunting reserve for the Maharaja of Gwalior.',
        keyFauna: ['Leopard', 'Chinkara', 'Nilgai', 'Golden Jackal', 'Sambar'],
        keyFlora: ['Teak', 'Sal', 'Kardhai'],
        coordinates: { lat: 25.65, lng: 77.72 },
        climate: 'Semi-Arid',
        bestTime: 'November to April',
        entryFee: '₹30 (Indian), ₹250 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Panna_national_park.jpg/960px-Panna_national_park.jpg'
    },
    {
        id: 'guindy',
        name: 'Guindy National Park',
        state: 'Tamil Nadu',
        stateId: 'tn',
        established: 1976,
        area: 2.7,
        areaUnit: 'km²',
        type: 'National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            'One of the few national parks inside a metropolitan city (Chennai). It serves as a vital green lung and maintains dry evergreen scrub forests.',
        keyFauna: ['Blackbuck', 'Chital', 'Jackal', 'Star Tortoise', 'Spotted Deer'],
        keyFlora: ['Dry Evergreen Scrub', 'Deciduous Trees'],
        coordinates: { lat: 13.01, lng: 80.23 },
        climate: 'Tropical Wet and Dry',
        bestTime: 'Year-round',
        entryFee: '₹20 (Indian), ₹100 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Guindy_National_Park_47_Children_Play_Area.jpg/960px-Guindy_National_Park_47_Children_Play_Area.jpg'
    },
    {
        id: 'gulf-of-mannar',
        name: 'Gulf of Mannar Marine National Park',
        state: 'Tamil Nadu',
        stateId: 'tn',
        established: 1980,
        area: 560,
        areaUnit: 'km²',
        type: 'Marine National Park',
        isTigerReserve: false,
        isUNESCO: false,
        description:
            'Comprises 21 small islands along the coast. It is a marine biosphere reserve protecting coral reefs, seagrass beds, and the endangered Dugong.',
        keyFauna: ['Dugong', 'Sea Turtle', 'Dolphin', 'Corals', 'Whale Shark'],
        keyFlora: ['Coral Reefs', 'Seagrass', 'Mangroves'],
        coordinates: { lat: 9.12, lng: 78.97 },
        climate: 'Tropical Marine',
        bestTime: 'October to March',
        entryFee: '₹50 (Indian), ₹500 (Foreign)',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/View_of_Gulf_of_Mannar_from_Rameshwaram%2C_Tamil_Nadu.jpg/960px-View_of_Gulf_of_Mannar_from_Rameshwaram%2C_Tamil_Nadu.jpg'
    }
];

const TIGER_RESERVES = NATIONAL_PARKS.filter(p => p.isTigerReserve);

const UNESCO_SITES = NATIONAL_PARKS.filter(p => p.isUNESCO);

const WILDLIFE_SPECIES = [
    {
        name: 'Bengal Tiger',
        icon: '🐅',
        status: 'Endangered',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Royal_Bengal_Tiger_at_Nandankanan.jpg/960px-Royal_Bengal_Tiger_at_Nandankanan.jpg',
        description:
            "The national animal of India. India hosts about 70% of the world's wild tigers across 50+ reserves.",
        parks: [
            'jim-corbett',
            'ranthambore',
            'kanha',
            'bandhavgarh',
            'periyar',
            'sundarbans',
            'bandipur',
            'nagarhole',
            'tadoba',
            'pench'
        ]
    },
    {
        name: 'Asiatic Lion',
        icon: '🦁',
        status: 'Endangered',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Panthera_leo_persica%28Asiatic_Lion%29_Gir.jpg/960px-Panthera_leo_persica%28Asiatic_Lion%29_Gir.jpg',
        description:
            "Found exclusively in Gujarat's Gir Forest. Conservation brought the population from under 20 to over 600.",
        parks: ['gir']
    },
    {
        name: 'Snow Leopard',
        icon: '🐆',
        status: 'Vulnerable',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Snow_Leopard_Closeup_%2813883260104%29.jpg/960px-Snow_Leopard_Closeup_%2813883260104%29.jpg',
        description:
            'The ghost of the mountains, found in the high Himalayas and Ladakh. Hemis hosts the highest density worldwide.',
        parks: ['hemis', 'great-himalayan', 'dachigam', 'nanda-devi', 'valley-of-flowers']
    },
    {
        name: 'One-Horned Rhinoceros',
        icon: '🦏',
        status: 'Vulnerable',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/One_horned_Rhino.jpg/960px-One_horned_Rhino.jpg',
        description: "Two-thirds of the world's population lives in Kaziranga. India's conservation success story.",
        parks: ['kaziranga']
    },
    {
        name: 'Asian Elephant',
        icon: '🐘',
        status: 'Endangered',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Asian_Elephant_Bull_%28Elephas_maximus%29_%287856743588%29.jpg/960px-Asian_Elephant_Bull_%28Elephas_maximus%29_%287856743588%29.jpg',
        description: 'India has the largest population of Asian elephants. Found in southern and northeastern forests.',
        parks: ['jim-corbett', 'kaziranga', 'periyar', 'bandipur', 'nagarhole', 'bannerghatta']
    },
    {
        name: 'Indian Leopard',
        icon: '🐆',
        status: 'Vulnerable',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Indian-Leopard.jpg/960px-Indian-Leopard.jpg',
        description:
            "Widely distributed across India's forests. Adapts to diverse habitats from rainforests to dry deciduous forests.",
        parks: ['jim-corbett', 'ranthambore', 'kanha', 'bandhavgarh', 'nagarhole', 'tadoba']
    },
    {
        name: 'Hangul (Kashmir Stag)',
        icon: '🦌',
        status: 'Critically Endangered',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/The_Last_Surviving_Population_of_Hangul.jpg/960px-The_Last_Surviving_Population_of_Hangul.jpg',
        description: 'Found only in Dachigam. One of the most endangered deer species with fewer than 200 remaining.',
        parks: ['dachigam']
    },
    {
        name: 'Lion-Tailed Macaque',
        icon: '🐒',
        status: 'Endangered',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/THE_LION-TAILED_MACAQUE.jpg/960px-THE_LION-TAILED_MACAQUE.jpg',
        description: 'Endemic to the Western Ghats, this distinctive primate has a lion-like mane around its face.',
        parks: ['periyar', 'silent-valley']
    },
    {
        name: 'Nilgiri Tahr',
        icon: '🐐',
        status: 'Endangered',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Nilgiri_Tahr_Eravikulam_National_Park.jpg/960px-Nilgiri_Tahr_Eravikulam_National_Park.jpg',
        description:
            'An endangered mountain goat species endemic to the Nilgiri Hills and Western Ghats of southern India.',
        parks: ['eravikulam']
    },
    {
        name: 'Great Indian Bustard',
        icon: '🐦',
        status: 'Critically Endangered',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Great_Indian_bustard.jpg/960px-Great_Indian_bustard.jpg',
        description:
            'One of the heaviest flying birds, found in the Thar Desert. Fewer than 150 individuals remain in the wild.',
        parks: ['desert']
    },
    {
        name: 'Dugong',
        icon: '🐬',
        status: 'Vulnerable',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Dugong_Marsa_Alam.jpg/960px-Dugong_Marsa_Alam.jpg',
        description:
            'The sea cow, found in the warm coastal waters of the Gulf of Mannar. A gentle herbivorous marine mammal.',
        parks: ['gulf-of-mannar']
    },
    {
        name: 'Barasingha',
        icon: '🦌',
        status: 'Endangered',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Swamp_Deer_Barasingha.jpg/960px-Swamp_Deer_Barasingha.jpg',
        description: 'The swamp deer, saved from extinction by Kanha. Known for its magnificent 12-point antlers.',
        parks: ['kanha']
    },
    {
        name: 'Gaur (Indian Bison)',
        icon: '🐃',
        status: 'Vulnerable',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Gaur%28Bos_gaurus%29.jpg/960px-Gaur%28Bos_gaurus%29.jpg',
        description: "The world's largest extant bovine, found in the forests of southern and central India.",
        parks: ['kanha', 'bandhavgarh', 'bandipur', 'nagarhole', 'tadoba', 'pench']
    }
];

const STATES = [
    { id: 'all', name: 'All India', region: 'all' },
    { id: 'uk', name: 'Uttarakhand', region: 'north' },
    { id: 'up', name: 'Uttar Pradesh', region: 'north' },
    { id: 'rj', name: 'Rajasthan', region: 'north' },
    { id: 'hp', name: 'Himachal Pradesh', region: 'north' },
    { id: 'jk', name: 'Jammu and Kashmir', region: 'north' },
    { id: 'la', name: 'Ladakh', region: 'north' },
    { id: 'mp', name: 'Madhya Pradesh', region: 'central' },
    { id: 'mh', name: 'Maharashtra', region: 'west' },
    { id: 'gj', name: 'Gujarat', region: 'west' },
    { id: 'ka', name: 'Karnataka', region: 'south' },
    { id: 'kl', name: 'Kerala', region: 'south' },
    { id: 'tn', name: 'Tamil Nadu', region: 'south' },
    { id: 'as', name: 'Assam', region: 'northeast' },
    { id: 'br', name: 'Bihar', region: 'east' },
    { id: 'wb', name: 'West Bengal', region: 'east' },
    { id: 'or', name: 'Odisha', region: 'east' },
    { id: 'ar', name: 'Arunachal Pradesh', region: 'northeast' }
];
