// Indian Festival Calendar — Data Module

const FESTIVALS = [
  { id: "diwali", name: "Diwali", english: "Festival of Lights", month: 10, day: 20, duration: 5, category: "Hindu", region: "Pan-India", description: "The most celebrated Hindu festival symbolizing the victory of light over darkness, good over evil. Homes are decorated with diyas (oil lamps), rangoli, and fireworks.", traditions: ["Lighting diyas", "Rangoli", "Fireworks", "Gift exchange", "Puja to Lakshmi"], food: ["Sweets (ladoo, barfi)", "Namak pare", "Chakli", "Karanji"], significance: "Lord Rama's return to Ayodhya after 14 years", color: "#f59e0b", icon: "🪔" },
  { id: "holi", name: "Holi", english: "Festival of Colors", month: 3, day: 14, duration: 2, category: "Hindu", region: "North India", description: "The vibrant festival of colors celebrating spring, love, and the triumph of good over evil. People throw colored powder (gulal) and water at each other.", traditions: ["Playing with colors", "Holika Dahan (bonfire)", "Music and dance", "Water guns (pichkari)"], food: ["Gujiya", "Thandai", "Puran Poli", "Malpua"], significance: "Victory of Prahlad over Holika, divine love of Radha-Krishna", color: "#ec4899", icon: "🎨" },
  { id: "navratri", name: "Navratri / Durga Puja", english: "Nine Nights", month: 10, day: 10, duration: 9, category: "Hindu", region: "Pan-India (varies)", description: "Nine nights celebrating the divine feminine (Shakti). Garba/Dandiya in Gujarat, Durga Puja in Bengal, Ramlila in North India, Golu in South India.", traditions: ["Garba/Dandiya Raas", "Durga Puja pandals", "Fasting", "Kanya Puja", "Ramlila performances"], food: ["Fasting foods (kuttu, singhare)", "Sabudana khichdi", "Malpua"], significance: "Goddess Durga's victory over Mahishasura", color: "#ef4444", icon: "💃" },
  { id: "ganesh_chaturthi", name: "Ganesh Chaturthi", english: "Birthday of Ganesha", month: 9, day: 1, duration: 10, category: "Hindu", region: "Maharashtra, Pan-India", description: "Celebrating the birth of Lord Ganesha, remover of obstacles. Elaborate clay idols are installed in homes and public pandals, then immersed in water.", traditions: ["Idol installation", "Daily aarti", "Cultural programs", "Visarjan (immersion)"], food: ["Modak", "Ladoo", "Karanji", "Puran Poli"], significance: "Birth of Lord Ganesha", color: "#f97316", icon: "🐘" },
  { id: "onam", name: "Onam", english: "Harvest Festival", month: 9, day: 15, duration: 10, category: "Hindu", region: "Kerala", description: "Kerala's biggest festival celebrating the annual homecoming of legendary King Mahabharata. Features the spectacular Onam Sadhya feast and snake boat races.", traditions: ["Pookalam (flower carpet)", "Onam Sadhya feast", "Vallam Kali (boat race)", "Pulikali (tiger dance)", "Kaikottikali"], food: ["Onam Sadhya (26+ dishes)", "Payasam", "Avial", "Sambar"], significance: "King Mahabali's annual visit", color: "#22c55e", icon: "🌺" },
  { id: "pongal", name: "Pongal / Makar Sankranti", english: "Harvest Festival", month: 1, day: 14, duration: 4, category: "Hindu", region: "South India", description: "Tamil harvest festival thanking the Sun God. The ritual boiling of rice in milk until it overflows symbolizes abundance. Celebrated with kolam (rangoli), cattle decoration.", traditions: ["Pongal cooking ritual", "Kolam/Rangoli", "Cattle decoration (Mattu Pongal)", "Jallikattu (bull taming)"], food: ["Sweet Pongal (chakkarai)", "Ven Pongal", "Payasam"], significance: "Sun's northward journey (Uttarayana)", color: "#eab308", icon: "☀️" },
  { id: "dussehra", name: "Dussehra / Vijayadashami", english: "Victory of Good", month: 10, day: 22, duration: 1, category: "Hindu", region: "Pan-India", description: "Celebrating Lord Rama's victory over Ravana. Giant Ravana effigies are burned in North India. In Mysore, the grand Dasara procession showcases royal heritage.", traditions: ["Ravana Dahan (effigy burning)", "Ramlila performances", "Mysore Palace illumination", "Weapons worship (Ayudha Puja)"], food: ["Festive meals", "Sweets"], significance: "Rama's victory over Ravana", color: "#ef4444", icon: "🔥" },
  { id: "christmas", name: "Christmas", english: "Birth of Jesus", month: 12, day: 25, duration: 1, category: "Christian", region: "Pan-India", description: "Celebrated with great enthusiasm across India. Goa's midnight mass, Kolkata's Park Street lights, Mumbai's bands at Bandra. Indian Christians add unique local flavors.", traditions: ["Midnight Mass", "Christmas tree", "Gift exchange", "Caroling", "Star decorations"], food: ["Christmas cake", "Neureos", "Bakarwadi", "Vindaloo"], significance: "Birth of Jesus Christ", color: "#22c55e", icon: "🎄" },
  { id: "eid_ul_fitr", name: "Eid-ul-Fitr", english: "Festival of Breaking Fast", month: 4, day: 10, duration: 1, category: "Muslim", region: "Pan-India", description: "Celebrating the end of Ramadan's holy month of fasting. Marked by special prayers, feasts, gift-giving, and community gatherings. Imtehan gatherings bring families together.", traditions: ["Eid prayers (Namaz)", "Feast preparation", "Eidi (gifts)", "Community gatherings", "Sevaiyan (vermicelli)"], food: ["Sevaiyan", "Biryani", "Sheer Khurma", "Kebabs", "Kheer"], significance: "End of Ramadan fasting", color: "#22c55e", icon: "🌙" },
  { id: "baisakhi", name: "Baisakhi", english: "Punjabi New Year", month: 4, day: 14, duration: 1, category: "Sikh", region: "Punjab", description: "Sikh harvest festival and New Year, also marking the founding of the Khalsa by Guru Gobind Singh. Celebrated with Bhangra, fairs, and special prayers at Gurdwaras.", traditions: ["Bhangra and Giddha", "Nagar Kirtan (procession)", "Langar (community meal)", "Fair (mela)"], food: ["Langar (community feast)", "Makki di Roti & Sarson ka Saag", "Kheer"], significance: "Foundation of Khalsa (1699)", color: "#eab308", icon: "🌾" },
  { id: "buddha_purnima", name: "Buddha Purnima", english: "Birthday of Buddha", month: 5, day: 12, duration: 1, category: "Buddhist", region: "Pan-India", description: "Celebrating the birth, enlightenment, and death of Gautama Buddha. Especially significant at Bodh Gaya, Sarnath, and Kushinagar with special prayers and processions.", traditions: ["Meditation sessions", "Temple visits", "Processions", "Dana (giving)"], food: ["Vegetarian meals", "Prasad"], significance: "Birth and enlightenment of Buddha", color: "#a855f7", icon: "☸️" },
  { id: "raksha_bandhan", name: "Raksha Bandhan", english: "Bond of Protection", month: 8, day: 19, duration: 1, category: "Hindu", region: "North India", description: "Celebrating the sacred bond between brothers and sisters. Sisters tie decorative threads (rakhis) on brothers' wrists, who promise to protect them.", traditions: ["Rakhi tying ceremony", "Aarti", "Gift exchange", "Sweet distribution"], food: ["Sweets", "Special meals"], significance: "Brother-sister bond of protection", color: "#ec4899", icon: "🪢" },
  { id: "janmashtami", name: "Krishna Janmashtami", english: "Birthday of Krishna", month: 8, day: 26, duration: 2, category: "Hindu", region: "Pan-India", description: "Celebrating the birth of Lord Krishna. Midnight celebrations, Dahi Handi (human pyramid breaking curd pot), and Raslila performances.", traditions: ["Dahi Handi", "Midnight aarti", "Raslila", "Fasting"], food: ["Makhan Mishri", "Panjiri", "Kheer"], significance: "Birth of Lord Krishna", color: "#6366f1", icon: "🪈" },
];

const FESTIVAL_MONTHS = [
  { month: 1, name: "January", festivals: ["Pongal / Makar Sankranti", "Lohri", "Republic Day"] },
  { month: 2, name: "February", festivals: ["Basant Panchami", "Maha Shivaratri"] },
  { month: 3, name: "March", festivals: ["Holi", "Ugadi / Gudi Padwa", "Chaitra Navratri"] },
  { month: 4, name: "April", festivals: ["Baisakhi", "Buddha Purnima", "Eid-ul-Fitr"] },
  { month: 5, name: "May", festivals: ["Vat Savitri Vrat", "Buddha Purnima"] },
  { month: 6, name: "June", festivals: ["Rath Yatra", "Eid-ul-Adha", "Hariyali Teej"] },
  { month: 7, name: "July", festivals: ["Guru Purnima", "Ker Sthapana"] },
  { month: 8, name: "August", festivals: ["Raksha Bandhan", "Krishna Janmashtami", "Independence Day", "Onam"] },
  { month: 9, name: "September", festivals: ["Ganesh Chaturthi", "Pitrupaksha", "Navratri begins"] },
  { month: 10, name: "October", festivals: ["Navratri / Durga Puja", "Dussehra", "Diwali"] },
  { month: 11, name: "November", festivals: ["Diwali", "Chhath Puja", "Guru Nanak Jayanti"] },
  { month: 12, name: "December", festivals: ["Christmas", "New Year's Eve"] },
];

const REGIONAL_FESTIVALS = [
  { name: "Lohri", region: "Punjab", season: "Winter", description: "Bonfire festival celebrating harvest and winter solstice. Songs, peanuts, rewri thrown into fire.", icon: "🔥", color: "#f97316" },
  { name: "Ugadi / Gudi Padwa", region: "Karnataka / Maharashtra", season: "Spring", description: "New Year celebration marking the beginning of spring. Gudi (flag) hoisting, neem-jaggery consumption.", icon: "Flag", color: "#22c55e" },
  { name: "Bohag Bihu", region: "Assam", season: "Spring", description: "Assamese New Year and harvest festival. Traditional Bihu dance, feasts, and community gatherings.", icon: "💃", color: "#ec4899" },
  { name: "Chhath Puja", region: "Bihar / UP", season: "Autumn", description: "Ancient festival dedicated to Sun God. Fasting, offerings to setting and rising sun at riverbanks.", icon: "☀️", color: "#eab308" },
  { name: "Bihu", region: "Assam", season: "Seasonal", description: "Three Bihu festivals: Bohag (spring), Bhogali (harvest), Magh (winter). Central to Assamese identity.", icon: "🌾", color: "#22c55e" },
  { name: "Pongal", region: "Tamil Nadu", season: "Winter", description: "Four-day harvest festival. Bhogi (cleaning), Surya Pongal (cooking), Mattu Pongal (cattle), Kaanum Pongal (family).", icon: "☀️", color: "#f59e0b" },
  { name: "Gudi Padwa", region: "Maharashtra", season: "Spring", description: "Marathi New Year. Gudi (silk flag on bamboo) hoisted, shrikhand-puri feast, rangoli.", icon: "🎊", color: "#06b6d4" },
  { name: "Theyyam", region: "Kerala (North)", season: "Seasonal", description: "Ancient ritual dance form where performers become deities. Over 400 Theyyams performed in temples.", icon: "🎭", color: "#ef4444" },
  { name: "Hornbill Festival", region: "Nagaland", season: "Winter", description: "Nagaland's 'Festival of Festivals.' 16 tribal groups showcase their culture through dance, music, food, and crafts.", icon: "🦅", color: "#8b5cf6" },
  { name: "Pushkar Fair", region: "Rajasthan", season: "Autumn", description: "World's largest camel fair combined with Pushkar's Brahma temple pilgrimage. Camel trading, folk music, and competitions.", icon: "🐪", color: "#f97316" },
];

const FESTIVAL_INSIGHTS = [
  { title: "1.4 Billion Celebrants", icon: "🌍", body: "Indian festivals are among the largest human gatherings on Earth. Diwali alone involves over 1 billion people across 30+ countries. Kumbh Mela draws 120 million pilgrims over 49 days — visible from space.", color: "#f59e0b" },
  { title: "Seasonal Wisdom", icon: "🌦️", body: "Indian festivals follow the agricultural calendar. Makar Sankranti (winter solstice), Holi (spring arrival), Onam (harvest), Diwali (post-monsoon) — each festival is also a marker of natural cycles and farming rhythms.", color: "#22c55e" },
  { title: "Unity in Diversity", icon: "🤝", body: "India's festivals span every religion, region, and community — Hindu, Muslim, Sikh, Christian, Buddhist, Jain, Parsi. Each festival adds its color to India's mosaic, creating the most festival-rich nation on Earth.", color: "#06b6d4" },
  { title: "Economic Impact", icon: "💰", body: "Indian festivals drive massive economic activity. Diwali alone generates ₹2-3 lakh crore in consumer spending. Eid-ul-Fitr, Christmas, and Pongal similarly boost retail, food, and tourism sectors.", color: "#a855f7" },
  { title: "Cultural Preservation", icon: "📖", body: "Festivals are living museums. The Dahi Handi preserves Krishna legends, Theyyam maintains tribal spiritual traditions, and Rath Yatra keeps Jagannath worship alive. Each celebration is a transmission of cultural knowledge.", color: "#ec4899" },
  { title: "Fusion & Evolution", icon: "💡", body: "Indian festivals evolve while maintaining core traditions. Electric diyas replace oil lamps, online rakhis cross continents, and eco-friendly Ganesh idols address environmental concerns — tradition adapts without losing meaning.", color: "#3b82f6" },
];
