// Indian Meditation & Yoga Traditions — Data Module

const YOGA_TRADITIONS = [
  {
    id: "hatha",
    name: "Hatha Yoga",
    origin: "Rishikesh, Uttarakhand",
    period: "15th Century CE",
    founder: "Swatmarama",
    text: "Hatha Yoga Pradipika",
    description: "The foundational physical yoga system combining asanas (postures), pranayama (breathing), and shatkarma (cleansing) to prepare the body for deeper meditation.",
    keyAsanas: ["Surya Namaskar", "Padmasana", "Sirsasana", "Sarvangasana", "Paschimottanasana"],
    benefits: ["Physical strength", "Flexibility", "Breath control", "Mental focus", "Energy balance"],
    difficulty: "Beginner to Intermediate",
    philosophy: "Balance the solar (ha) and lunar (tha) energies in the body through physical practice.",
    regions: ["North India", "Rishikesh", "Haridwar"],
    modernPopularity: 85,
    color: "#f59e0b"
  },
  {
    id: "ashtanga",
    name: "Ashtanga Vinyasa",
    origin: "Mysore, Karnataka",
    period: "20th Century CE",
    founder: "K. Pattabhi Jois",
    text: "Yoga Korunta (attributed to Vamana Rishi)",
    description: "A dynamic, athletic style of yoga with a specific sequence of postures linked by breath (vinyasa). Practiced in a fixed series of increasing difficulty.",
    keyAsanas: ["Primary Series (Yoga Chikitsa)", "Intermediate Series (Nadi Shodhana)", "Advanced A/B/C"],
    benefits: ["Cardiovascular fitness", "Discipline", "Internal heat", "Detoxification", "Mental clarity"],
    difficulty: "Intermediate to Advanced",
    philosophy: "Eight limbs of yoga practiced in sequence to purify body and mind systematically.",
    regions: ["Mysore", "South India"],
    modernPopularity: 75,
    color: "#ef4444"
  },
  {
    id: "kundalini",
    name: "Kundalini Yoga",
    origin: "Punjab / Kashmir",
    period: "Ancient – 20th Century popularized",
    founder: "Yogi Bhajan (modern)", "Ancient tradition",
    text: "Kundalini Upanishad, Shiva Samhita",
    description: "Focuses on awakening the kundalini energy at the base of the spine through combination of postures, breathing techniques, chanting (mantra), and meditation.",
    keyAsanas: ["Breath of Fire", "Kriyas", "Sat Kriya", "Spinal Flex", "Ego Eradicator"],
    benefits: ["Energy awakening", "Spiritual awareness", "Stress relief", "Hormonal balance", "Intuition"],
    difficulty: "All levels",
    philosophy: "Awaken dormant spiritual energy (shakti) and raise it through chakras to the crown.",
    regions: ["Punjab", "Haryana", "Kashmir"],
    modernPopularity: 65,
    color: "#a855f7"
  },
  {
    id: "iyengar",
    name: "Iyengar Yoga",
    origin: "Pune, Maharashtra",
    period: "20th Century CE",
    founder: "B.K.S. Iyengar",
    text: "Light on Yoga",
    description: "Emphasizes precise alignment and use of props (blocks, straps, blankets) to make postures accessible. Known for therapeutic applications.",
    keyAsanas: ["All 200 classical asanas with props", "Wall Rope Yoga (Kurunta)", "Restorative Poses"],
    benefits: ["Therapeutic healing", "Precise alignment", "Accessibility", "Chronic pain relief", "Patience"],
    difficulty: "All levels",
    philosophy: "Correct form and sustained holding of postures leads to physical and mental transformation.",
    regions: ["Pune", "Maharashtra"],
    modernPopularity: 70,
    color: "#3b82f6"
  },
  {
    id: "bikram",
    name: "Bikram / Hot Yoga",
    origin: "Kolkata → Los Angeles",
    period: "20th Century CE",
    founder: "Bikram Choudhury",
    text: "Bikram's Beginning Yoga Class",
    description: "A set sequence of 26 postures and 2 breathing exercises practiced in a heated room (40°C/104°F). Designed to promote sweating and flexibility.",
    keyAsanas: ["Standing Head-to-Knee", "Standing Bow", "Camel Pose", "Locust Pose", "Spine Twisting"],
    benefits: ["Deep flexibility", "Sweat detoxification", "Cardiovascular challenge", "Weight management", "Focus"],
    difficulty: "Beginner to Intermediate",
    philosophy: "Heat opens the body, the fixed sequence systematically works every joint and muscle.",
    regions: ["Global influence"],
    modernPopularity: 60,
    color: "#f97316"
  },
  {
    id: "sivananda",
    name: "Sivananda Yoga",
    origin: "Rishikesh → Global",
    period: "20th Century CE",
    founder: "Swami Sivananda",
    text: "The Complete Illustration Book of Asanas",
    description: "A gentle, classical approach emphasizing 5 principles: proper exercise, proper breathing, proper relaxation, proper diet, and positive thinking/meditation.",
    keyAsanas: ["12 Basic Asanas + Sun Salutation", "Shoulder Stand", "Headstand", "Forward Bend", "Cobra"],
    benefits: ["Holistic wellness", "Gentle progression", "Spiritual growth", "Stress management", "Community"],
    difficulty: "Beginner",
    philosophy: "Through selfless service, positive thinking, and classical yoga practice, one achieves self-realization.",
    regions: ["Rishikesh", "Global"],
    modernPopularity: 55,
    color: "#22c55e"
  },
  {
    id: "tantra",
    name: "Tantra Yoga",
    origin: "Kashmir / Northeast India",
    period: "5th–12th Century CE",
    founder: "Abhinavagupta (Kashmir Shaivism)",
    text: "Vijnanabhairava Tantra, Netra Tantra",
    description: "A esoteric path using body, energy, and consciousness practices to transcend duality. Includes visualization, energy work, mantra, and ritual.",
    keyAsanas: ["Chakra visualization", "Bandhas (energy locks)", "Mudras", "Dharana practices"],
    benefits: ["Energy mastery", "Consciousness expansion", "Emotional integration", "Spiritual liberation", "Creativity"],
    difficulty: "Advanced",
    philosophy: "The body is a temple; through its sacred practices, one realizes the unity of all existence.",
    regions: ["Kashmir", "Assam", "Bengal", "Tamil Nadu"],
    modernPopularity: 35,
    color: "#ec4899"
  },
  {
    id: "viniyoga",
    name: "Viniyoga",
    origin: "Tamil Nadu",
    period: "Ancient – 20th Century",
    founder: "T.K.V. Desikachar",
    text: "The Heart of Yoga",
    description: "Adapts yoga practices to individual needs. Emphasizes the therapeutic application of yoga techniques tailored to each person's condition.",
    keyAsanas: ["Individualized sequences", "Breath-synchronized movement", "Therapeutic applications"],
    benefits: ["Personalized practice", "Therapeutic", "Gentle", "Adaptable", "Evidence-based"],
    difficulty: "All levels",
    philosophy: "Yoga must be adapted to the individual, not the individual to yoga.",
    regions: ["Chennai", "Tamil Nadu"],
    modernPopularity: 40,
    color: "#06b6d4"
  }
];

const MEDITATION_TECHNIQUES = [
  {
    id: "dhyana",
    name: "Dhyana (Mindfulness Meditation)",
    origin: "Vedic Tradition",
    description: "The practice of sustained, focused awareness on a single object — breath, mantra, or visual point — without judgment or reaction.",
    method: "Sit comfortably, focus attention on breath or object. When mind wanders, gently return. Practice 10–45 minutes.",
    benefits: ["Reduced anxiety", "Emotional regulation", "Improved focus", "Self-awareness", "Inner peace"],
    difficulty: "Beginner",
    duration: "10–45 minutes",
    bestTime: "Early morning (Brahma Muhurta)",
    chakra: "Ajna (Third Eye)",
    color: "#6366f1"
  },
  {
    id: "trataka",
    name: "Trataka (Candle Gazing)",
    origin: "Hatha Yoga Tradition",
    description: "Concentrated gazing at a single point — typically a candle flame — to develop one-pointed concentration and activate the ajna chakra.",
    method: "Place a candle at eye level, 3-4 feet away. Gaze without blinking until tears form. Close eyes and visualize the afterimage.",
    benefits: ["Enhanced concentration", "Eye strengthening", "Mental clarity", "Psychic development", "Insomnia relief"],
    difficulty: "Beginner to Intermediate",
    duration: "10–20 minutes",
    bestTime: "Evening (dusk)",
    chakra: "Ajna (Third Eye)",
    color: "#eab308"
  },
  {
    id: "nadishodhana",
    name: "Nadi Shodhana (Alternate Nostril)",
    origin: "Hatha Yoga Pradipika",
    description: "Balancing breath technique that alternates airflow between left (ida/lunar) and right (pingala/solar) nostrils to harmonize energy channels.",
    method: "Close right nostril, inhale left. Close both, retain. Release right, exhale. Inhale right. Close both, retain. Release left, exhale. One round.",
    benefits: ["Energy balance", "Calming effect", "Improved breathing", "Nervous system regulation", "Hormonal balance"],
    difficulty: "Beginner",
    duration: "5–15 minutes",
    bestTime: "Before meditation or morning",
    chakra: "Vishuddha (Throat)",
    color: "#06b6d4"
  },
  {
    id: "kundalini_meditation",
    name: "Kundalini Meditation",
    origin: "Tantric Tradition",
    description: "Awakening the dormant kundalini shakti energy through specific kriyas (techniques), breathwork, and mantras to raise consciousness through the chakras.",
    method: "Combine specific kriya (posture + breath + mantra + mudra). Practice daily at same time for 40+ days (sadhana).",
    benefits: ["Spiritual awakening", "Energy elevation", "Expanded awareness", "Emotional release", "Intuitive development"],
    difficulty: "Intermediate to Advanced",
    duration: "11–31 minutes (kriya-specific)",
    bestTime: "Early morning (4:00–7:00 AM)",
    chakra: "All 7 Chakras",
    color: "#a855f7"
  },
  {
    id: "mantra",
    name: "Mantra Japa (Chanting)",
    origin: "Vedic Tradition",
    description: "Repetition of sacred syllables or phrases (mantras) to focus the mind and invoke specific energetic qualities. Can be done silently or aloud.",
    method: "Choose a mantra (Om, Gayatri, or personal). Repeat 108 times using a mala (prayer beads). Focus on vibration and meaning.",
    benefits: ["Mental calming", "Vibrational healing", "Devotional connection", "Concentration", "Positive affirmations"],
    difficulty: "Beginner",
    duration: "5–30 minutes",
    bestTime: "Brahma Muhurta (4-6 AM)",
    chakra: "Vishuddha (Throat)",
    color: "#f59e0b"
  },
  {
    id: "yoga_nidra",
    name: "Yoga Nidra (Yogic Sleep)",
    origin: "Tantric Tradition",
    description: "Guided meditation that systematically rotates awareness through body, breath, emotions, and visualization while remaining on the threshold of sleep.",
    method: "Lie in Shavasana. Follow guided instructions through 8 stages: Sankalpa, Rotation of Consciousness, Breath Awareness, Opposites, Visualization, etc.",
    benefits: ["Deep relaxation", "PTSD relief", "Sleep improvement", "Stress reduction", "Subconscious reprogramming"],
    difficulty: "Beginner",
    duration: "20–60 minutes",
    bestTime: "Before sleep or after lunch",
    chakra: "Ajna to Sahasrara",
    color: "#8b5cf6"
  },
  {
    id: "vipassana",
    name: "Vipassana (Insight Meditation)",
    origin: "Theravada Buddhist (Indian origin)",
    description: "Systematic observation of bodily sensations to develop insight into impermanence (anicca), suffering (dukkha), and non-self (anatta).",
    method: "Sit still, observe natural breath. Scan body from head to feet, noting sensations without reaction. Practice 10-day intensive retreats for deep practice.",
    benefits: ["Equanimity", "Self-observation", "Liberation from suffering", "Emotional mastery", "Body awareness"],
    difficulty: "Intermediate",
    duration: "60 minutes (standard) to 10-day retreats",
    bestTime: "4:00–6:30 AM",
    chakra: "Ajna (Third Eye)",
    color: "#22c55e"
  },
  {
    id: "soham",
    name: "Soham Meditation",
    origin: "Upanishadic Tradition",
    description: "The natural mantra — 'So' on inhalation (I am That), 'Ham' on exhalation (That I am). The most universal and effortless mantra meditation.",
    method: "Breathe naturally. Mentally repeat 'So' with inhalation, 'Ham' with exhalation. No counting, no effort. Simply merge with the breath.",
    benefits: ["Effortlessness", "Self-realization", "Deep peace", "Unity consciousness", "No equipment needed"],
    difficulty: "Beginner",
    duration: "Unlimited",
    bestTime: "Anytime",
    chakra: "Anahata (Heart)",
    color: "#10b981"
  }
];

const CHAKRAS = [
  { id: "muladhara", name: "Muladhara", english: "Root Chakra", color: "#ef4444", element: "Earth", location: "Base of spine", mantra: "LAM", seed: "L", petal: 4, description: "Foundation of energy system. Governs survival, security, grounding, and physical identity.", blockage: "Fear, anxiety, instability", awakening: "Feeling safe, grounded, and connected to earth", icon: "🔴" },
  { id: "svadhisthana", name: "Svadhisthana", english: "Sacral Chakra", color: "#f97316", element: "Water", location: "Below navel", mantra: "VAM", seed: "V", petal: 6, description: "Center of creativity, pleasure, sexuality, and emotional flow.", blockage: "Guilt, emotional numbness, addiction", awakening: "Creative expression, healthy relationships, emotional fluidity", icon: "🟠" },
  { id: "manipura", name: "Manipura", english: "Solar Plexus Chakra", color: "#eab308", element: "Fire", location: "Solar plexus", mantra: "RAM", seed: "R", petal: 10, description: "Center of personal power, willpower, confidence, and transformation.", blockage: "Shame, powerlessness, digestive issues", awakening: "Confidence, determination, inner fire, leadership", icon: "🟡" },
  { id: "anahata", name: "Anahata", english: "Heart Chakra", color: "#22c55e", element: "Air", location: "Heart center", mantra: "YAM", seed: "Y", petal: 12, description: "Center of love, compassion, forgiveness, and emotional healing.", blockage: "Grief, jealousy, inability to forgive", awakening: "Unconditional love, empathy, compassion, inner peace", icon: "💚" },
  { id: "vishuddha", name: "Vishuddha", english: "Throat Chakra", color: "#06b6d4", element: "Ether", location: "Throat", mantra: "HAM", seed: "H", petal: 16, description: "Center of communication, self-expression, truth, and authenticity.", blockage: "Fear of speaking, dishonesty, thyroid issues", awakening: "Authentic expression, clear communication, truthfulness", icon: "🔵" },
  { id: "ajna", name: "Ajna", english: "Third Eye Chakra", color: "#6366f1", element: "Light", location: "Between eyebrows", mantra: "OM", seed: "AUM", petal: 2, description: "Center of intuition, wisdom, imagination, and inner vision.", blockage: "Confusion, lack of direction, headaches", awakening: "Intuitive clarity, insight, imagination, wisdom", icon: "🟣" },
  { id: "sahasrara", name: "Sahasrara", english: "Crown Chakra", color: "#a855f7", element: "Cosmic Energy", location: "Top of head", mantra: "Silence / AUM", seed: "Silence", petal: 1000, description: "Gateway to higher consciousness, spiritual connection, and divine unity.", blockage: "Spiritual disconnection, cynicism, depression", awakening: "Enlightenment, cosmic consciousness, spiritual liberation", icon: "⚪" }
];

const PRANAYAMA_TECHNIQUES = [
  { id: "ujjayi", name: "Ujjayi", english: "Victorious Breath", description: "Slight constriction of the glottis creating an ocean-like sound. Used in most yoga practices.", benefits: ["Calms nervous system", "Improves focus", "Internal heating", "Warms body"], duration: "5–20 minutes", difficulty: "Beginner", color: "#3b82f6" },
  { id: "kapalbhati", name: "Kapalabhati", english: "Skull-Shining Breath", description: "Forceful exhalations with passive inhalations. Cleanses the respiratory system and energizes the mind.", benefits: ["Energizing", "Detoxification", "Mental clarity", "Core strengthening"], duration: "3–5 minutes", difficulty: "Intermediate", color: "#f59e0b" },
  { id: "bhastrika", name: "Bhastrika", english: "Bellows Breath", description: "Forceful inhalations and exhalations through the nose, like a pair of bellows. Generates intense internal heat.", benefits: ["Maximum energy", "Metabolism boost", "Mental alertness", "Detoxification"], duration: "1–3 minutes", difficulty: "Advanced", color: "#ef4444" },
  { id: "sheetali", name: "Sheetali", english: "Cooling Breath", description: "Inhale through a curled tongue (or between teeth), creating a cooling sensation. Reduces body temperature.", benefits: ["Body cooling", "Stress reduction", "Thirst relief", "Anger management"], duration: "5–15 minutes", difficulty: "Beginner", color: "#22c55e" },
  { id: "bhramari", name: "Bhramari", english: "Humming Bee Breath", description: "Inhale deeply, then hum like a bee on exhalation with ears closed. Produces a resonant vibration in the head.", benefits: ["Anxiety relief", "Blood pressure reduction", "Sinus clearing", "Sleep aid"], duration: "5–10 minutes", difficulty: "Beginner", color: "#a855f7" },
  { id: "nadi_shodhana", name: "Nadi Shodhana", english: "Alternate Nostril Breathing", description: "Alternating breath between left and right nostrils to balance the nervous system and energy channels.", benefits: ["Nervous system balance", "Calming", "Focus enhancement", "Hormonal regulation"], duration: "5–15 minutes", difficulty: "Beginner", color: "#06b6d4" },
];

const FAMOUS_PRACTITIONERS = [
  { name: "Patanjali", era: "2nd Century BCE", contribution: "Compiled the Yoga Sutras — the foundational text of classical yoga with 196 sutras on eight limbs.", tradition: "Raja Yoga", notable: "Father of Classical Yoga" },
  { name: "Swami Vivekananda", era: "1863–1902", contribution: "Introduced yoga and Vedanta philosophy to the Western world at the 1893 Parliament of Religions.", tradition: "Raja/Jnana Yoga", notable: "Global Yoga Ambassador" },
  { name: "T. Krishnamacharya", era: "1888–1989", contribution: "The 'Father of Modern Yoga.' Revived Hatha Yoga and influenced Ashtanga, Iyengar, and Viniyoga traditions.", tradition: "Haṭha Yoga", notable: "Guru of gurus" },
  { name: "B.K.S. Iyengar", era: "1918–2014", contribution: "Developed Iyengar Yoga emphasizing precise alignment and props. Authored 'Light on Yoga' — the yoga bible.", tradition: "Iyengar Yoga", notable: "Light on Yoga author" },
  { name: "K. Pattabhi Jois", era: "1915–2009", contribution: "Popularized Ashtanga Vinyasa yoga globally from his Mysore school. Created the modern vinyasa flow style.", tradition: "Ashtanga Yoga", notable: "Mysore school founder" },
  { name: "Maharishi Mahesh Yogi", era: "1918–2008", contribution: "Popularized Transcendental Meditation (TM) globally, counterculture icon. Taught The Beatles.", tradition: "TM/Vedic Meditation", notable: "TM founder" },
  { name: "Bhagwan Shree Rajneesh (Osho)", era: "1931–1990", contribution: "Combined Zen, Sufi, and tantric meditation techniques into dynamic and surrender meditation practices.", tradition: "Neo-Sannyas", notable: "Dynamic Meditation creator" },
  { name: "Sri Sri Ravi Shankar", era: "1956–", contribution: "Founded Art of Living and the Sudarshan Kriya breathing technique, taught to millions worldwide.", tradition: "Vedic/Wedantic", notable: "Art of Living founder" },
  { name: "Baba Ramdev", era: "1965–", contribution: "Popularized yoga among Indian masses through TV. Promoted Patanjali products and yoga as daily practice.", tradition: "Hatha/Kundalini", notable: "Yoga TV pioneer" },
];

const YOGA_SUTRAS = [
  { sutra: 1.1, sanskrit: "अथ योगानुशासनम्", translation: "Now, the discipline of yoga begins.", section: "Samadhi Pada", theme: "Beginning" },
  { sutra: 1.2, sanskrit: "योगश्चित्तवृत्तिनिरोधः", translation: "Yoga is the cessation of the fluctuations of the mind.", section: "Samadhi Pada", theme: "Definition" },
  { sutra: 1.3, sanskrit: "तदा द्रष्टुः स्वरूपेऽवस्थानम्", translation: "Then the seer abides in their own true nature.", section: "Samadhi Pada", theme: "Liberation" },
  { sutra: 2.46, sanskrit: "स्थिरसुखम् आसनम्", translation: "Posture should be steady and comfortable.", section: "Sadhana Pada", theme: "Asana" },
  { sutra: 2.49, sanskrit: "तस्य प्रत्याशासेषक्रमः", translation: "Pranayama follows after that — regulation of the life force.", section: "Sadhana Pada", theme: "Pranayama" },
  { sutra: 2.55, sanskrit: "तेन वशी तत्वानाम्", translation: "Through that [mastery of pranayama], one gains mastery over the elements.", section: "Sadhana Pada", theme: "Mastery" },
  { sutra: 3.2, sanskrit: "जप प्रच्छर्दनम्", translation: "Repetition [of a mantra] with contemplation of its meaning.", section: "Vibhuti Pada", theme: "Mantra" },
  { sutra: 3.3, sanskrit: "तज्जपस्तदर्थभावनम्", translation: "From that repetition, the essence of the mantra is realized.", section: "Vibhuti Pada", theme: "Realization" },
];
